apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedbase-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedbase-api
  template:
    metadata:
      labels:
        app: embedbase-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: embedbase-api
        image: cerit.io/cerit/embedbase:v0.4
        imagePullPolicy: Always
        env:
        - name: PORT
          value: '8080'
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              key: uri
              name: embedbase-db-app
        - name: OPENAI_APIKEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_APIKEY
              name: openai
        - name: OPENAI_ORGANISATION
          valueFrom:
            secretKeyRef:
              key: OPENAI_ORGANISATION
              name: openai
        - name: DIMENSIONS
          value: "768"
        - name: OPENAI_MODEL
          value: 'nomic-embed-text:latest'
        - name: OPENAI_URL
          value: 'http://ollama.ollama-ns.svc.cluster.local:11434/v1/'
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 8
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /config.yaml 
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
         name: config
